2021 updates
one-pace/one-pace-web-client pull request #26
Opened 2021-05-12 01:46 UTC by jhlav

2021-07-04 19:59 UTC, sewil requested changes

2021-07-04 19:59 UTC, sewil commented on src/components/torrents.js
> +          <div />
This looks a bit hacky having to add an empty div here. Is there no way to solve this using flexbox for example?

2021-07-05 19:53 UTC, jhlav commented on src/components/torrents.js
> +          <div />
That is deliberate.  It evens out the positioning of the middle section so it appears as it always has, but with the right side containing the sidebar with the Discord widget.

Technically this can be avoided using CSS Grid, but the browser support is less and the V1 codebase doesn't have as many polyfills and browser compatibility fixes as V2 ("next" branch).

2021-07-06 14:47 UTC, sewil approved these changes

2021-07-06 14:47 UTC, merged